utils::globalVariables(
  c(".id",  ".stid",  "MID", "OWNER", "VIEW_NAME", "a", "b", "child",
    "afli", "aflvisir", "aldur", "ar", "area_swept",
    "artal", "astand", "aths", "audkenni", "bauja", "beita", "botndypi", "botndypi_hift",
    "botndypi_kastad", "botnhiti", "botnhiti_lok", "breidd", "breidd_lok", "bridle_length",
    "brl", "bruttoruml", "bruttotonn", "bt", "catch", "category_no", "code",
    "comments", "cs", "cs_iso2", "cs_prefix", "dags", "dags_fundid",
    "dagstimi", "date_time_utc", "dekk", "departure", "departure_port_no", "depth",
    "depth_end", "depth_reg", "descr", "drattur_hefst", "drattur_lykur", "dummy", "dypi",
    "dypi_lok", "effort", "effort_unit", "eigandi", "einknr", "einkst", "eng_descr", "engine_kw",
    "enskt_heiti", "eykt", "fi_veidarfaeri", "fishing_end",
    "fishing_start", "fisktegund", "fisktegund_id", "fiskur_id", "fj_kroka",
    "fj_kyngreint", "fj_maelt", "fj_magasyna", "fj_talid", "fj_vigtad", "fjoldi", "flagname",
    "flokkur", "foreign", "fteg", "gear_no", "genital", "geoconvert1", "gid", "gid2", "gid_old",
    "gid_temp", "gidc", "gildrur", "globalid", "grandarar", "gross_registered_ton", "gt",
    "gutted", "gv", "haed", "hafnarnumer", "hafsvaedi_id", "harborid", "heading",
    "headline_length", "heildarafli", "heimah", "heimahofn", "heiti", "hid", "hift_breidd",
    "hift_lengd", "hift_v", "hitastig", "hlerar", "hlutfall", "hoflina", "hofn", "i_gildi",
    "ibotni", "id", "identification", "identification_no", "idx", "imo", "imonr",
    "imonumber", "in_out_of_harbor", "iso2", "iso2a", "isscfg", "kallmerki", "kastad_breidd",
    "kastad_lengd", "kastad_v", "klst", "klukkan", "komunr", "kvarna_nr", "kvarnadir", "kyn",
    "kyn_nr", "kynfaeri", "kynthroski", "kynthroski_nr", "l_dags", "landing",
    "landing_port_no", "landshluti_id", "last_analyzed", "lat", "lat2", "latitude",
    "latitude_end", "ldags", "leidangur", "lengd", "lengd_lok", "length_class",
    "length_reg", "lhofn", "lifur", "linu_ivilnun", "liver", "localid", "lods_veidarfaeri",
    "logn_hefst", "lon", "lon2", "londun_hefst", "londun_id", "longitude", "longitude_end",
    "lower", "lpad", "lysing", "lysing_enska", "m_sek", "maeldir", "maeling_id", "magi", "magn",
    "magn_oslaegt", "magn_slaegt", "man", "manudur", "max_towlength", "mclass",
    "measure_type", "medal_lengd_neta", "merki_id", "mesh_size", "mestalengd", "mid",
    "min_towlength", "mmsi", "mmsi.mid", "mmsi_vessel", "mname", "mobileid", "moskvi",
    "moskvi_minnsti", "nafnskips", "name", "nbreidd", "net_nr", "notkunarteg", "num_rows",
    "numer", "on.bottom", "otterboard_weight", "owner", "pl_breidd", "port", "posdate",
    "poslat", "poslon", "power_index", "propeller_diameter", "r_talid", "recdate",
    "reiknistudull", "reitur", "rek_adili", "rlat", "rlon", "rn", "saga_nr",
    "sample_category_no", "sample_id", "sclass", "select", "selj", "sex_no",
    "sexual_maturity_id", "simi", "sjondypi", "skip_hradi", "skip_nafn", "skip_nr",
    "skip_numer", "skip_stefna", "skipaflokkur", "skipnr", "skrad_breidd", "skrad_dypt",
    "skrad_lengd", "skradbreidd", "skraddypt", "skradlengd", "skyring", "slaegt", "smareitur",
    "species", "species_no", "speed", "sq", "st", "stada", "station", "station_id",
    "std_towlength", "std_width", "stod_id", "stomach",
    "stratum", "sur", "sweeps", "sy", "synaflokkur", "synaflokkur_nr", "synis_id", "t1", "t2",
    "table_name", "tablespace_name", "taldir", "taudkenni", "tegund", "tegund_nr",
    "thvermskrufu", "thyngd", "tid", "time", "timi", "tlen", "tmat",
    "tog_nr", "togbyrjun", "togendir", "toghradi", "toglengd", "tognumer", "togtimi",
    "towlength", "towtime", "trip_id", "tsex", "tsid", "twgt", "uid", "umdnr", "uno", "uppsj_hiti",
    "uppsj_hiti_lok", "uppsjavarhiti", "ur_gildi", "utgafa", "uthaldsdagar", "vclass",
    "vedags", "veidarf", "veidarfaeri", "veidarfaeri_id", "veidikerfi", "veidistofn",
    "veidisvaedi", "vel_kw", "vessel", "vessel_csprefix", "vessel_mid", "vessel_no",
    "vesselclass", "vesselname", "vid", "vid2", "vid_mmsi", "vindatt", "vindstig",
    "vinnsluhofn", "visinda_heiti", "visir", "vlengd", "vocabulary", "weight", "width_reg",
    "year", "yfirbordshiti", "z2",
    "column_name", "count", "nvl", "sql", "to_char", "to_date", "to_number", "view_name",
    "."))